### ISSUE TITLE
CU: Solicitar aval

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#10]
Documentar e implementar *CU Solicitar aval*.

- [x] Documentar CU
- [x] Implementar CU
- [x] Testing

**Comment by jonduttweiler** [comment]
Implementado en branch https://github.com/ACDI-Argentina/avaldao-dapp/tree/issue-10-solicitar-aval 
Falta testearlo para integrarlo en master
