### ISSUE TITLE
Documentar despliegue de Avaldao

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#16]
Documentar despliegue de Avaldao como está en Give4Forests: https://github.com/ACDI-Argentina/efem-crowdfunding-dapp/wiki/EFEM-Crowdfunding-deploy

Incluir la documentación acá: https://github.com/ACDI-Argentina/avaldao/wiki

**Comment by jonduttweiler** [comment]
Documentación incluida en https://github.com/ACDI-Argentina/avaldao/wiki/Despliegue
