### ISSUE TITLE
Preparar ambiente de desarrollo

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#17]
Se requiere preparar el ambiente de desarrollo de Avaldao según las instrucciones con Docker.

https://github.com/ACDI-Argentina/avaldao-docker

Leer la documentación de negocio desde la wiki:  https://github.com/ACDI-Argentina/avaldao/wiki

**Comment by ebanchio** [comment]
Aún usando la versión 10.20.1 de node, tuve problemas con librerías que utilizan TextEncoder y TextDecoder y las modifiqué manualmente para poder compilar el contrato.
