### ISSUE TITLE
Construir servicio común de usuarios

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#19]
Se requiere tener un servicio de Feathers encargado de almacenar y autenticar usuarios.

Este servicio debe poder accederse con Give4Forests y Avaldao. Éste debe reemplazar el servicio de Feathers de Give4Forests.

> Avaldado debe tener su propio servicio de Feathers para Avales y demás entidades.

**Comment by jonduttweiler** [comment]
- [x] Agregar referencia al servicios de usuarios desde avaldao-docker en desarrollo
- [x] Crear un fork a partir del efem-feathers con el npmbre efem-users-feathers

**Comment by jonduttweiler** [comment]
Se lleva el seguimiento del  proyecto de usuarios en https://github.com/ACDI-Argentina/efem-users-feathers
