### ISSUE TITLE
Autenticación no funciona

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#21]
La autenticación no está funcionando a partir de la firma del mensaje.

El usuario queda siempre en estado no autenticado (*user.authenticated=false*).

**Comment by jonduttweiler** [comment]
Se realizaron cambios en [732ec1d](https://github.com/ACDI-Argentina/avaldao-dapp/commit/732ec1da29ee17c03b6e6909c4638ff77b7d706a) para actualizar el estado de user.authenticated.
