### ISSUE TITLE
Adaptar uso de branches

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#32]
A partir del Epic 3, debe adaptarse el uso de los branches, siguiendo los siguientes principios.

1. Debe haber una única rama de desarrollo principal en cada repo, denominada **master**.
2. Debe crearse una rama de *feature* o *fix* a partir del **master** por cada issue en el que se trabaje.
3. Debe crearse una rama denominada **beta**, donde se integre el trabajo terminado para desplegar en el ambiente Beta. Para esto debe adaptarse el Action de deploy.

**Comment by jonduttweiler** [comment]
Se creo la rama beta y se actualizo el action para que haga los despliegues para la dapp
