### ISSUE TITLE
Diseño de interfaz de usuario

### ISSUE THREAD

**Issue by ebanchio** [ACDI-Argentina/avaldao#36]
Issue para condensar los requerimientos sobre presentación de las secciones de la aplicación.

En principio la home del usuario contendrá la siguiente información:

- Información del fondo de garantía
- Avales que requieren atención/acción por parte del usuario.
- Listado de avales

**Comment by ebanchio** [comment]
El domingo 02/01 envié el siguiente correo a Lucía Cueto (diseñadora gráfica) para comenzar con esta tarea:

_Hola Lucía!_

_Recién me pongo a ver las cuestiones a cerrar antes de irme de vacaciones y me doy cuenta que nunca te escribí como para darte algunas indicaciones que te puedan servir para avanzar con AvalDAO._

_Entiendo que te juntarás con Mauricio para ver cuestiones relacionadas con la estética general del sitio (y con el famoso branding que comentaban en la reunión del otro día)._

_Eso probablemente te llevará un tiempo, pero de todas formas si te parece que podés ver algunas cuestiones que puedan mejorar lo que ya está implementado, podés darte una vuelta por http://beta.avaldao.com y proponer cambios con total libertad (en iconografía, disposición, terminología, etc...). Si bien se te comentó brevemente, lo que se ve en esa interfaz es:_
_1) Un detalle de cómo está constituído el fondo de garantía (una especie de balance)._
_2) El listado de avales que surgen de ese fondo de garantía, con una breve descripción y estado de cada uno._
_Te comento, pero sin ánimos de sesgar, que pensábamos que el ítem 2 podría dividirse en 2 listados: uno con aquellos avales que requieren alguna intervención pronta del usuario que está conectado y otro con el listado de todos los avales de ese fondo._

_Por cualquier duda, creo que voy a tener señal cada tanto como para poder responderte. No tengo problema._

_Muchas gracias!! Nos vemos a la vuelta._
_Saludos!_

**Comment by ebanchio** [comment]
El día 25/01 pasé a Lucía capturas de los circuitos implementados hasta ese momento en la aplicación. Estoy a la espera de los bocetos que arme. Quedamos en que pase lo que vaya teniendo para que pueda avanzar más rápido en la integración.

**Comment by ebanchio** [comment]
Adjunto link al [proyecto de Figma](https://www.figma.com/file/zZZtHBjwx7x80SRK4QQQqc/Wireframes-AVALDAO?node-id=0%3A1) en el que se están trabajando los bocetos.

**Comment by ebanchio** [comment]
El menú del usuario debería tener las siguientes opciones:
- Registrarse
- Editar perfil
- Acerca de
- Mi espacio
- Listado de Usuarios

**Comment by cmauriciocoronel** [comment]
@ebanchio habría que hacer estos pequeños ajustes visuales:

- [ ] Botón conectar wallet: una vez que el usuario se autentica, el botón debe mostrar un ícono a la derecha (ExpandMore) para indicar que hay más opciones y otro ícono (ExpandLess) para indicar que puede cerrarse el menú. Ver: https://v4.mui.com/components/material-icons
- [x] El favicon debe actualizarse por el de Avaldao.
- [ ] Incorporar nuevos estilos a las pantallas de avales diseñada por Lucía.
- [x] Agregar sección en header: FAQ, Acerca de, etc

**Comment by cmauriciocoronel** [comment]
Agrego los cambios solicitados por Mauricio Moresco.

[landing.pptx](https://github.com/ACDI-Argentina/avaldao/files/8605340/landing.pptx)
[LANDING.docx](https://github.com/ACDI-Argentina/avaldao/files/8605343/LANDING.docx)

**Comment by ebanchio** [comment]
Puntos resueltos:
- Esquema de funcionamiento en landingPage actualizado (propuesto por Mauricio).
- Textos correspondientes a carousel y platformFeatures actualizados (propuesto por Mauricio).
- Header con links para las secciones FAQ y ¿Qué es AvalDAO?, y mejoras visuales al encabezado (propuesto por Mauricio)
- Imágenes de carousel actualizadas (propuesto por Lucía)
- Fuente _Encode Sans_ unificada para toda la aplicación (propuesto por Lucía).
- FavIcon actualizado.

Puntos pendientes propuestos por Lucía:
- Nuevos estilos para las interfaces de avales: solicitud y visualización (especificación en proyecto de figma).
- Nuevos estilos para las interfaces de alta y modificación de perfil (especificación en proyecto de figma).
- Botón conectar wallet: una vez que el usuario se autentica, el botón debe mostrar un ícono a la derecha (ExpandMore) para indicar que hay más opciones y otro ícono (ExpandLess) para indicar que puede cerrarse el menú. Ver: https://v4.mui.com/components/material-icons.

Puntos pendientes propuestos por Mauricio:
- Modificación de textos para cards en landingPage: soy inversor, solicito un aval (especificación en landing.pptx, slide 9).
- Redirecciones desde los botones de presentes en landingPage: en carousel, platformFeatures, card _soy inversor_, card _solicito un aval  (especificación en landing.pptx, slides 2 a 5).
- Modificación visual del fondo de garantía (especificación en landing.pptx, slide 10).
- Completar links en footer (especificación en proyecto de figma y con aporte de Mauricio en landing.pptx, slide 11).

En proceso:
- Sección _Somos AvalDAO_ linkeado al item del encabezado _¿Qué es AvalDAO?_ Explica en detalle el funcionamiento de la plataforma (especificación en proyecto de figma).

**Comment by cmauriciocoronel** [comment]
Gracias @ebanchio.

Este issue se cierra ya que con el detalle se desglosaron los pedidos en los issues #64, #65, #66, #67, #68, #69, #70, #71 y #72.
