### ISSUE TITLE
Preparar ambiente de Producción

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#42]
Se requiere preparar el ambiente de Producción para instalar toda la solución de Avaldao, de manera análoga al ambiente Beta.

Construir un branch denomido _prod_ para que los Actions de Github realicen el despliegue desde allí.

- [x] Documentación
- [x] Despliegue

**Comment by jonduttweiler** [comment]
Se creo una nueva vm en digital ocean (137.184.62.240) en la cual se instalo docker y docker-compose.
Se agregon entradas en la zona dns del hosting apuntando a la misma (dapp.avaldao.com, feathers.avaldao.com).
Falta crear/revisar configuracion del docker-compose de produccion y hacer el deploy

**Comment by jonduttweiler** [comment]
- Se agregaron los actions correspondientes sobre el repositorio de la dapp y feathers. En ambos casos la rama se llama **production**. 
- Se creo una nueva base en mongo atlas para el ambiente de produccion,  solamente accesible desde la vm donde se ejecuta feathers.
- Se creo el servicio de usuarios para el ambiente de produccion, disponible en https://users.give4forest.org.  
- Se genero un nuevo JWT_SECRET para el servicio anterior, y se configuro avaldao feathers para que utilice el mismo. Por cuestiones de seguridad el mismo se maneja por fuera del sistema de versionado.
- Se actualizó la documentación.

Falta actualizar give 4 forest en el ambiente productivo para que utilice el servicio de usuarios. Revisar si hay usuarios en la base y migrarlos a la del servicio.

**Comment by cmauriciocoronel** [comment]
Para realizar ahora:

- [x] Agregar dominio https://users.avaldao.com, el cual debe apuntar al mismo host que https://users.give4forest.org/. Configurar la dapp para que funciones con https://users.avaldao.com.
- [x] TEMPORALMENTE configurar la dapp y feathers para que funciones con el smart contract de Testnet.

Para realizar una vez que cerremos el smart contract:
- [x] Desplegar el smart contract en Mainnet.
- [ ] Configurar la dapp y feathers para que funciones con el smart contract de Mainnet.

**Comment by cmauriciocoronel** [comment]
Se configuró el ambiente de Producción con el cron de desbloqueo de fondos de avales.

Instrucciones: https://github.com/ACDI-Argentina/avaldao/wiki/Disenio#desbloqueo-autom%C3%A1tico-de-fondos

**Comment by cmauriciocoronel** [comment]
@jonduttweiler estos son los datos del despliegue en Mainnet:

https://github.com/ACDI-Argentina/avaldao/wiki/Releases#v101

Podrías por favor actualizar la configuración de la dapp y feathers de usuarios? Gracias.
