### ISSUE TITLE
Editar aval

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#51]
Se requiere de la edición de un aval.

Crear método `aval.allowEdit(user)`. Se permite editar cuando el usuario `user` está autenticado y es el *Solicitante* y el aval está en estado `Solicitado`.

- [x] Documentar caso de uso
- [x] Implementar

**Comment by jonduttweiler** [comment]
Implementado en branch issue-51-editar-aval. Falta integrar a master
