### ISSUE TITLE
Probar dapp con Wallet Connect

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#57]
Probar la aplicación con Wallet Conecct en lugar de Metamask.

Probar el circuito completo, incluido también la firma offline.

**Comment by jonduttweiler** [comment]
Se realizaron las siguientes pruebas, utilizando defiant:

✅ conectar wallet
✅ autenticar usuario
✅ solicitar aval
❌ aceptar aval
✅ firmar aval offline

En el caso de la aceptación del aval, no se detecta desde la dapp que la transaccion ha sido confirmada en la wallet. 
Creo que puede estar relacionado con este issue:  [#3891] (https://github.com/ChainSafe/web3.js/issues/3891)

**Comment by BigMadCode** [comment]
He estado intentando de confirmar si es el mismo issue. Wallet connect me esta dando muchos problemas con Send Transaction y cualquier fetch con metamask.  Las transacciones se envian y metamask las procesa, pero wallet connect nunca retorna nada.... Alguien mas ve esto?

**Comment by jonduttweiler** [comment]
Al hacer más pruebas con wallet connect, usando Defiant como wallet , se encontró que el problema está relacionado con la longitud del campo data de la transacción que se envía. Si la misma tiene mas de 804 bytes, la misma nunca es enviada.
En Avaldao el problema se da en la funcion saveAval, la cual recibe como parametro un array con los timestamp de cuotas.
Según pruebas, un aval de 4 cuotas, tiene un array de 8 timestamps, genera un campo data de 772 bytes y es procesado correctamente. En cambio si probamos un aval de 5 cuotas, el mismo nunca es procesado.

En todos los casos la solicitud de confirmación llega a la wallet, y luego de confirmarla la misma falla silenciosamente, incluso no se muestra en el estado de transacciones realizadas en la wallet.

**Comment by cmauriciocoronel** [comment]
La integración funciona, incluyendo la aceptación del aval con Metamask App. Ver Issue #93.
