### ISSUE TITLE
El componente FondoGarantia no debe depender de los estilos del landing page

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#59]
Cada componte es una unidad independiente de los demás componentes. Esto permite el desacoplamiento y la reunitilización.

El componente `FondoGarantia` está dependiendo de los estilos definidos en la landing page:

```
import styles from "assets/jss/material-kit-react/views/**landingPageSections**/fondoGarantiaStyle.js";
```

Los estilos del componente deben estar dentro del componente o en su defecto en un archivo de estilos propio.

Además, dentro del archivo se está utilizando un nombre de variable que no corresponde con el componente `FondoGarantia`: `platformFeaturesStyle` .

**Comment by ebanchio** [comment]
Resuelto en commit 69afeac

**Comment by ebanchio** [comment]
Resuelto en commit 69afeac
