### ISSUE TITLE
El componente Cifras está requiriendo valores de redux no utilizados

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#60]
El componente `Cifras` está requiriendo los siguientes valores de Redux, y no se utilizan en el componente: `currentUser`, `tokenBalances`, `fondoGarantiaBalanceFiat`.

Esto requiere de la ejecución de `selectors` innecesarios.

Se requiere quitar los selectors que no sean necesarios para el componente.

**Comment by ebanchio** [comment]
Resuelto en commit 69afeac. Ya no fue necesario el componente Cifras luego de reestructurar FondoGarantia.
