### ISSUE TITLE
El componente CryptoAmount es dependiente del componente que lo invoque

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#61]
El componente `CryptoAmount` depende si o si de que el componente que lo invoque lo haga con la clase css `classes.amount`.

Esto hace muy dificil el mantenimiento de los componentes porque dejan de ser independientes y por lo tanto se acoplan.

El componente está siendo utilizado por otros componentes que no le están especificando el estilo y por lo tanto fallarán al acceder a la clase CSS `amount` de un objeto no definido.

Se requiere diseñar e implementar los componentes poniendo atención en su independencia. En este caso, el componente `CryptoAmount` podría recibir una `prop` opcional `color` para modificar su color.

**Comment by ebanchio** [comment]
Resuelto en commit 69afeac con una prop opcional.
