### ISSUE TITLE
Agregar sección Somos AvalDAO

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#71]
Agregar la pantalla `Somos AvalDAO` especificada en [Figma](https://www.figma.com/file/zZZtHBjwx7x80SRK4QQQqc/Wireframes-AVALDAO?node-id=21%3A176).

Esta sección debe estar vinculada desde el encabezado `Qué es AvalDAO`

**Comment by cmauriciocoronel** [comment]
Se requiere adaptar el item del carousel según la slice 3 del issue #72.

![image](https://user-images.githubusercontent.com/16942632/166837593-b7a2defa-6e75-4840-980d-8d1d89f0c23a.png)

**Comment by ebanchio** [comment]
Sección agregada.
