### ISSUE TITLE
Diseño de íconos de sponsors

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#74]
Se solicitó la construcción de una sección de sponsors de Avaldao (Issue #72, slice 11) y se construyó lo siguiente:

_Partnerships_

![image](https://user-images.githubusercontent.com/16942632/167228593-6c823722-142e-49c3-9aa1-d4aef6622557.png)

_Inversores_

![image](https://user-images.githubusercontent.com/16942632/167228606-79ba0752-0d94-4b4c-b0f2-4dd129e18c32.png)

_Wallets_

![image](https://user-images.githubusercontent.com/16942632/167228622-846ef23c-f916-4534-b55b-31839a4e83b4.png)

Se requiere diseñar la sección y los íconos de tal manera que la visualización presente un estilo homogéneo, flat preferentemente. Ver ejemplos: https://www.sovryn.app, https://tropykus.com. Si se considera en el diseño, se podrían descargar algunos íconos desde aquí: https://www.sovryn.app.

Se adjuntan los íconos actuales.

![acdi](https://user-images.githubusercontent.com/16942632/167228768-9a691ed4-c3c2-4ef4-bbc3-49a4fbf8d6fa.png)
![el-futuro-esta-en-el-monte](https://user-images.githubusercontent.com/16942632/167228770-c57d4d02-1555-43f7-a431-432686575575.png)
![IDB-Lab](https://user-images.githubusercontent.com/16942632/167228772-bfa0b96a-aa21-4e14-a11c-9cba16d894d5.gif)
![iovlabs](https://user-images.githubusercontent.com/16942632/167228773-b3f42d17-99e6-4b65-b3ac-4159af0e1d38.jpg)
![metamask](https://user-images.githubusercontent.com/16942632/167228774-54b9e0c4-4679-4517-ac82-937e3a501f60.svg)
![rsk](https://user-images.githubusercontent.com/16942632/167228776-8058401d-86a5-4775-a13e-1fc4ddba0d7c.svg)

**Comment by lucueto** [comment]
Hola! Consulto, la sección tiene que estar dividida con pestañas? Hay algún planteo hecho en Figma del tema pero no de esta modalidad sino tipo grilla horizontal. 
Gracias!

**Comment by cmauriciocoronel** [comment]
Hola Lu! Ví que en Figma está de esta manera.

![image](https://user-images.githubusercontent.com/16942632/167256889-7e56fffb-8ebf-4f0d-afe4-b88180d038b9.png)

En este caso lo solicitó Mauricio Moresco en base otras plataformas y clasificación del rol de cada sponsor, por lo que se requiere que esté dividido en pestañas. Si se te ocurre otra propuesta para dividir qué rol cumple cada sponsor, es bienvenida.

Gracias!!

**Comment by ebanchio** [comment]
Se puede utilizar la regla de css
_**filter: grayscale(100%);**_
para pasar a escala de gris los íconos.

**Comment by cmauriciocoronel** [comment]
Impacto el cambio a través de CSS.

**Comment by lucueto** [comment]
Ya dejé en Figma una propuesta de diseño para este contenido
https://www.figma.com/file/zZZtHBjwx7x80SRK4QQQqc/Wireframes-AVALDAO?node-id=0%3A1

**Comment by cmauriciocoronel** [comment]
Se impactó el diseño solicitado.

![image](https://user-images.githubusercontent.com/16942632/168190023-53b50aac-6cb4-4a25-aba5-6452358a0a5b.png)

![image](https://user-images.githubusercontent.com/16942632/168190048-ccef438c-7317-47bc-9cc0-2e0d90d9bad8.png)

![image](https://user-images.githubusercontent.com/16942632/168190076-61983373-18f8-42d1-8630-53809994f5b3.png)
