### ISSUE TITLE
Revisión de UI y UX

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#77]
Se requiere una revisión general de la interface de usuario y de la usabilidad de Avaldao en el ambiente beta: https://beta.avaldao.com

También pueden hacerse observaciones a nivel de contendio. Mauricio Moresco ha estado trabajando en esto también.

Una vez hecha las observaciones, se requiere escribirlas aquí en este issue para luego planificar su implementación/corrección.

**Comment by lucueto** [comment]
Revisión general de la interfaz (UI)

GENERAL
- Márgenes y espacios internos
- Tamaños en carrousel
- Pestañas y carrousel de Aliados
- Revisar cards de imágenes (replanteo de opción sin foto)
- Revisar writting (Español neutro o sudamericano | signos de puntuación) *unificar*
- Mis inversiones-suscripción

DASHBOARD
- Ajustar gráfico de torta
- Fondo de garantía txt

BOTONES
- Sombras  
- Correspondencia de uso en cada caso (Ej en carrousel, en cards, etc)
.- Respuesta al click
- Denominaciones (ej."SUMATE")

DEUDAS
- Road map (Rediseño/incorporación de check box ya propuesta)
- Diseño de página de error
- Progress bar
- Loader
- Notifications
- Search field

**Comment by lucueto** [comment]
**Recomiendo hacer algunas pruebas de usuario**

**Comment by cmauriciocoronel** [comment]
Gracias Lu.

Podrías adjuntar los íconos de los checkboxs en formato SVG por favor? No los puedo descargar desde Figma.

![image](https://user-images.githubusercontent.com/16942632/170281246-0eb14725-882b-448c-9579-e56d93258cb2.png)

**Comment by lucueto** [comment]
![form-input-4](https://user-images.githubusercontent.com/104791670/170572139-0ff063e7-12ce-478e-a53e-c7446f49d286.svg)
![form-input-5](https://user-images.githubusercontent.com/104791670/170572141-2a6472a9-0f37-4adb-8db3-2e8257714607.svg)
![form-input-2](https://user-images.githubusercontent.com/104791670/170572143-1c6d6ac6-0844-4a4c-9689-f587abd95978.svg)
![form-input-3](https://user-images.githubusercontent.com/104791670/170572146-e1761b49-2998-4f5e-9a70-9d3d2db3f826.svg)

**Comment by lucueto** [comment]
Mauri, por si sirve, también les dejo acá cómo bajar los elemenos desde el programa
![image](https://user-images.githubusercontent.com/104791670/170572427-b2a94d99-d61a-45d3-8d56-7c9ff638b47f.png)

**Comment by lucueto** [comment]
![image](https://user-images.githubusercontent.com/104791670/170597700-e9f03165-695a-44b1-a304-db71f8f1b2f4.png)
![ion_rocket-outline](https://user-images.githubusercontent.com/104791670/170597972-2bfc2506-790d-479c-a8ea-fb0e1a127bc0.svg)
![form-check-input](https://user-images.githubusercontent.com/104791670/170598130-59111328-50b3-49c5-ac03-bda9d238f861.svg)

**Comment by cmauriciocoronel** [comment]
Perfecto Lu, gracias por la explicación. Pude descargar los iconos desde Figma.

Se impactaron los siguientes cambios en la aplicación:

- Road map (Rediseño/incorporación de check box ya propuesta): Se corrigieron los checkbox según los diseñados.
- Diseño de página de error: Se mejoró la presentación de la página de error.

Los demás puntos no tengo especificaciones de qué corregir exactamente. Por el momento quedarán como guías de mejoras en futuros releases mientras la aplicación se libera.
