### ISSUE TITLE
Revisar imagenes de inversores y solictitantes

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#78]
Revisar por ejemplo este apartado:

![image](https://user-images.githubusercontent.com/16942632/168313320-ef85efe3-63f8-4807-85c5-fc2094bb9550.png)

Las imágenes no están en línea con el diseño general de la pantalla. Diseñar algo acorde al diseño general de la pantalla.

**Comment by lucueto** [comment]
No entiendo ésto: "Diseñar algo acorde al diseño general de la pantalla."
Son fotografías ejemplares, ¿decís que busque otras, o que hagamos una solución diferente a las cards?

**Comment by cmauriciocoronel** [comment]
La imágenes no coinciden con el diseño de los recursos de la página. Debieran seguir esta línea:

![image](https://user-images.githubusercontent.com/16942632/168365856-42bf044e-77af-4d20-8f39-d20983d9ccc9.png)

Manejarlo con cards me parece que está bien.

**Comment by lucueto** [comment]
El planteo era usar esas ilustraciones y además fotografías, dependiendo el caso. Entiendo el punto de todos modos.
Voy a ver si consigo de ese pack ilustraciones, si no habrá que rever el diseño de las cards para eliminar la parte ilustrativa del espacio

**Comment by lucueto** [comment]
![ACDI - AvalDAO-en-08](https://user-images.githubusercontent.com/104791670/168701670-b43fc0c4-de40-4885-b261-e7426353c33a.svg)
![ACDI - AvalDAO-ENg-08](https://user-images.githubusercontent.com/104791670/168701671-a9cb5427-340b-403f-b33c-3de44f776a69.svg)

**Comment by lucueto** [comment]
![Group 25](https://user-images.githubusercontent.com/104791670/169099680-ce6a3aad-06d9-48fa-b751-3d7f6f5240f3.png)

**Comment by lucueto** [comment]
Si ven una foto o imagen que refiera de mejor manera a cada rol, les agradecería mucho que la pasen así probamos. Mientras, la idea vendría por acá

**Comment by cmauriciocoronel** [comment]
Lu, podrías adjuntar las imagenes acá por separado por favor? No las puedo descargar desde Figma.
Gracias.

**Comment by lucueto** [comment]
![image 62](https://user-images.githubusercontent.com/104791670/169152162-8e78d247-c78e-414f-bb34-aadc16012e62.png)
![image 63](https://user-images.githubusercontent.com/104791670/169152171-b4cd2ce6-d437-4f08-b2c9-737ea333a660.png)

**Comment by cmauriciocoronel** [comment]
Se ajustaron los paneles de la siguiente manera.

![image](https://user-images.githubusercontent.com/16942632/169162022-69afc2b8-ec9e-451a-af69-6783a78bb464.png)
