### ISSUE TITLE
Construir diagrama de funcionamiento con mayor definición y en inglés

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/avaldao#83]
El diagrama de funcionamiento tiene una definición muy baja y no está alineado a la visualización de la página.

![diagramaFuncionamiento dcf6f3b7](https://user-images.githubusercontent.com/16942632/168345685-17706ce8-799b-424e-bae8-7891d842d59c.jpg)

Se requiere construir una imagen vectorial, con formato SVG para que la visualización no aparezca pixelada.

Además, Mauricio Moresco estará construyendo los textos en inglés de esta imagen.

**Comment by lucueto** [comment]
Modificado el archivo y reemplazado en Figma. Quedo a la espera de la versión en inglés, de todas formas los textos de la infografía no componen la imagen sino que están escritos en la página

**Comment by cmauriciocoronel** [comment]
Gracias @lucueto.

Podrías por favor adjuntar el diagrama acá o enviarmelo? No lo puedo descargar desde Figma.

**Comment by lucueto** [comment]
![ACDI - AvalDAO-09](https://user-images.githubusercontent.com/104791670/168673869-46d05e4b-c55e-487d-9945-56a9c2c6a6fd.svg)

**Comment by lucueto** [comment]
![ACDI - AvalDAO-09](https://user-images.githubusercontent.com/104791670/168673962-bfb7ec30-78be-41de-af55-2fdb2ffe3701.svg)

**Comment by lucueto** [comment]
![ACDI - AvalDAO-CURVAS-09](https://user-images.githubusercontent.com/104791670/168674254-ba6a383b-b7ec-4930-a88a-de4f833f1a86.svg)

**Comment by lucueto** [comment]
Mauri, lo paso en curvas y en tipos porque no sé el motivo por el cual se cambia de tipografía en este formato. No sé qué es más conveniente para uds así que te dejo las dos opciones

**Comment by lucueto** [comment]
![Uploading ACDI - AvalDAO-en-08.svg…]()

**Comment by cmauriciocoronel** [comment]
Muchas gracias Lu!

Para finalizar necesitaríamos el mismo diagrama pero en idioma inglés.

**Comment by lucueto** [comment]
![ACDI - AvalDAO-en-08](https://user-images.githubusercontent.com/104791670/168860419-41410bbf-7dcb-422b-89e0-4ab2d3850dde.svg)

**Comment by lucueto** [comment]
![ACDI - AvalDAO-ENg-08](https://user-images.githubusercontent.com/104791670/168860445-589afbec-2eb1-4fa9-b209-038f59cdc771.svg)

**Comment by cmauriciocoronel** [comment]
Lu, fijate que la imagen en inglés no tiene la imagen de la apartado de Shops.

**Comment by lucueto** [comment]
![ACDI - AvalDAO-encv-08](https://user-images.githubusercontent.com/104791670/168930089-c4947a72-1691-4bf2-9c14-49b2487f3aa8.svg)
![ACDI - AvalDAO-ENg-08-08](https://user-images.githubusercontent.com/104791670/168930092-7fea2de3-e1ac-4d4b-a6c3-f04423c5a0db.svg)

**Comment by lucueto** [comment]
![sp](https://user-images.githubusercontent.com/104791670/169074959-8748cc3d-66f7-4bf4-a3cf-51d373e77241.svg)
![en](https://user-images.githubusercontent.com/104791670/169074964-76d8ed5a-e6ee-4a37-b7ad-a954f2cfa8ea.svg)

Dejo la info con fondo blanco

**Comment by cmauriciocoronel** [comment]
Se actualizaron los diagramas en español e inglés con el fondo blanco.
Gracias Lu.
